import { useSupabaseQuery, useSupabaseMutation } from './useSupabaseQuery';
import { supabase } from '../supabase-config';
import type { RecipeWithIngredients, /* RecipeInsert, */ RecipeUpdate, RecipeIngredientInsert } from '../schemas/supabase-helpers';
import type { RecipeForm } from '../schemas/Recipes';
import { checkAuthenticatedSession } from '../utils/auth';

/**
 * Hook to fetch all recipes with their structured ingredients
 * Includes recipe_ingredient junction table data
 */
export function useRecipes() {
    const { data, error, isLoading } = useSupabaseQuery<RecipeWithIngredients>({
        table: 'recipe',
        select: '*, recipe_ingredient(*)',
    });

    return {
        recipes: data,
        isLoading,
        isError: error
    };
}

export function useRecipesByCategory(category: string) {
    return useSupabaseQuery<RecipeWithIngredients>({
        table: 'recipe',
        select: '*, recipe_ingredient(*)',
        filters: { category },
    });
}

export function useRecipesMutation() {
    return useSupabaseMutation('recipe');
}

/**
 * Add a new recipe with structured ingredients
 * Inserts into both recipe and recipe_ingredient tables
 */
async function addRecipe(recipe: RecipeForm): Promise<RecipeWithIngredients | null> {
    try {
        await checkAuthenticatedSession();

        // 1. Insert the recipe first and get the new ID
        const { data: recipeData, error: recipeError } = await supabase
            .from('recipe')
            .insert({
                name: recipe.name,
                url: recipe.url,
                ingredients: 'temp string cause ingredients in separate table'
            })
            .select()
            .single();

        if (recipeError) {
            throw new Error(recipeError.message);
        }

        // 2. If there are ingredients, insert them into recipe_ingredient table
        if (recipe.ingredients && recipe.ingredients.length > 0) {
            const recipeIngredientInserts: RecipeIngredientInsert[] = recipe.ingredients.map(ing => ({
                recipe_id: recipeData.id,
                ingredient_name: ing.name,
                quantity: ing.quantity,
                unit: ing.unit,
            }));

            const { error: recipeIngredientError } = await supabase
                .from('recipe_ingredient')
                .insert(recipeIngredientInserts);

            if (recipeIngredientError) {
                throw new Error(recipeIngredientError.message);
            }

            // Return recipe with ingredients
            return {
                ...recipeData,
                recipe_ingredient: recipeIngredientInserts.map(ing => ({
                    id: '', // Will be generated by DB
                    created_at: new Date().toISOString(),
                    recipe_id: ing.recipe_id,
                    ingredient_name: ing.ingredient_name,
                    quantity: ing.quantity ?? null,
                    unit: ing.unit ?? null,
                }))
            };
        }

        // Return recipe without ingredients
        return {
            ...recipeData,
            recipe_ingredient: []
        };
    } catch (error) {
        if (error instanceof Error) {
            throw error;
        }

        throw new Error('Failed to add recipe');
    }
}

/**
 * Update a recipe and its ingredients
 * Uses delete+reinsert pattern for ingredients
 */
async function updateRecipe(
    recipeId: string,
    updates: RecipeUpdate,
    ingredients: RecipeIngredientInsert[]
): Promise<RecipeWithIngredients | null> {
    try {
        await checkAuthenticatedSession();

        // 1. Update main recipe fields
        const { data: recipeData, error: recipeError } = await supabase
            .from('recipe')
            .update(updates)
            .eq('id', recipeId)
            .select()
            .single();

        if (recipeError) {
            throw new Error(recipeError.message);
        }

        // 2. Delete all old ingredients for this recipe
        const { error: deleteError } = await supabase
            .from('recipe_ingredient')
            .delete()
            .eq('recipe_id', recipeId);

        if (deleteError) {
            throw new Error(deleteError.message);
        }

        // 3. Insert fresh ingredient list
        if (ingredients && ingredients.length > 0) {
            const ingredientRows = ingredients.map(ing => ({
                recipe_id: recipeId,
                ingredient_name: ing.ingredient_name,
                quantity: ing.quantity,
                unit: ing.unit,
            } as RecipeIngredientInsert));

            const { error: insertError } = await supabase
                .from('recipe_ingredient')
                .insert(ingredientRows);

            if (insertError) {
                throw new Error(insertError.message);
            }

            return {
                ...recipeData,
                recipe_ingredient: ingredientRows.map(ing => ({
                    id: '',
                    created_at: new Date().toISOString(),
                    recipe_id: ing.recipe_id,
                    ingredient_name: ing.ingredient_name,
                    quantity: ing.quantity ?? null,
                    unit: ing.unit ?? null,
                }))
            };
        }

        return {
            ...recipeData,
            recipe_ingredient: []
        };
    } catch (error) {
        if (error instanceof Error) {
            throw error;
        }

        throw new Error('Failed to update recipe');
    }
}

/**
 * Delete a recipe
 * Ingredients are automatically deleted via CASCADE
 */
async function deleteRecipe(recipeId: string): Promise<void> {
    await checkAuthenticatedSession();

    const { error } = await supabase
        .from('recipe')
        .delete()
        .eq('id', recipeId);

    if (error) {
        throw new Error(error.message);
    }
}

export { addRecipe, updateRecipe, deleteRecipe };
